
## Methodology

The development of the Digital Capacity Index uses a mixed-methods approach:

1.  Data collected from international consultations, literature scans and interviews with Australian stakeholders have been used to build the database of relevant capacity definitions, metrics and indicators.
2.  Eight in-depth qualitative case studies has been conducted in parallel with other aspects of developing and evaluating the index and any associated instruments. These case studies illuminates the digital capacity challenges faced by particular communities and across three generations (children, their parents and their grandparents). This in-depth qualitative data is vital to communicating the diversity and complexity of the experience of digital capacity to policy makers, service providers and other vested parties. They identify specific aspects of capacity that warrant either adding new indicators, or weighting existing indicators. Data collected through these studies augment the quantitative evaluation.
3.  Development of a draft index and associated survey instrument, which have been  piloted with a convenience sample of (n=20) Australian families. The pilot involved a mix of online and offline administering of the survey, accompanied by a short series of open-ended questions designed to elicit feedback on the survey and any associated issues. Both quantitative and qualitative data have been used to refine the instrument.
4.  The Index are being progressively and iteratively refined based on the qualitative and pilot survey data before being run online with a targeted sample of 16 – 25, 45 – 60 and 65 – 75 year olds.
5.  Data has been analysed and compiled to produce a report on the digital capacity of Australian families.

These methods are coordinated within an integrated and holistic theoretical approach. We adapt and extend recent work – for example on digital safety and digital inclusion, which we view as a prerequisites but not equivalent to the broader idea of “digital capacity”. To establish a framework for assessing different dimensions of digital capacity, we propose drawing upon the [Circles of Social Life approach](http://www.circlesofsustainability.org/). Used by the United Nations Global Compact Cities Programme, the World Association of Major Metropolises, World Vision, and a number of local governments to support their engagement in cities, the approach treats social life as made up of four domains of practice — the economic, the ecological, the political and the cultural. In the context of digital capacity, we would identify and align specific indicators against each of these fields. We list some strictly indicative examples below:

* Economic:   capacity to use digital resources to improve job readiness; use of technology to derive income; perceived significance of digital skills and competencies in future employment
* Ecological:     levels of concern about online safety i.e. perceived safety and security operating in various online ‘spaces’; capacity to locate and deploy privacy and security tools; management of technology (both use and abuse) within the household; use of maps to understand local and global environments
* Political:  impact of online safety policy and legislation across generations; key sources of digital safety influence; use of digital media to stay informed about political events; capacity to mobilise or engage with others for political purposes through technology
* Cultural:   understanding of and resilience in dealing with digital safety issues; impact of informal learning on digital safety and participation; participation in cultural life through technology; active role as digital “facilitator” in cultural fields of family, neighbourhoods, and community groups.

The statistical data from the Index (the collection of which is deeply informed by the findings of the qualitative case studies) can be represented primarily in the form of ‘circles of social life’ diagrams, as well as through other data visualisation methods such as mapping and infographics. Mapped to these four domains, pilot results can be further analysed in terms of significant thematic and demographic hypotheses and relationships. For example, do young people with strong economic digital capacities translate those capacities to other spheres of social life? Or are there significant differences in how different generations exercise digital capacities in relation to sustaining cultural forms? The data gathered through the Index will therefore allow for important diagnostics about intergenerational and interdomain relationships, highlighting areas of community and social concern.

One key area the Index addresses explicitly is perceptions of and responses to digital safety issues. We propose that the deployment of “capacity”, along with the four domain model, forms a strong platform for interpreting these concerns – as inhibitors of the exercise of distinct capacities, rather than as a stand-alone area. As examples, perceived concern about political censorship or privacy acts as an inhibitor of the expression of free speech online; perceived concern about predation and vilification acts as an inhibitor of cultural expression. By discussing capacities as positive virtues of digital life, mapped against the four domains outlined above, the Index provides a robust platform from which to develop meaningful policy and practice interventions.
