
## Qualitative Findings


### Introduction

Digital technology has become critical to living well in contemporary society. As mobile and networked technologies become ubiquitous, enabling individuals, families and communities to maximize the benefits of the internet depends upon fostering fundamental 21st century capacities. These new capacities are central to the economic, political and cultural life of Australians and must be nurtured from early childhood, and through the life span, in households workplaces and communities. They include the necessary opportunities, skills, infrastructures, attitudes and behaviours to enable individuals and communities to identify risks and develop resilience while participating fully and meaningfully in digital life. Crucially, whilst these capacities are often thought about in individual terms (e.g. the capacity to keep oneself safe online), it is important that we begin to focus debate and target interventions around intergenerational and community-based capacities. Leveraging networks of support is vital in ensuring the maximum safety and participation of all users online.

This report summarises the key findings of one component of a larger project entitled Cultivating Digital Capacities being carried out by researchers at the Institute for Culture and Society at Western Sydney University and the Young and Well Cooperative Research Centre, in partnership with Google Australia. That initiative, in the first phase, aims to develop a conceptual framework around what we mean by digital capacities, and to develop an index that measures the digital capacities of Australian families. The index will provide a rigorous and holistic measure of digital capacities that combines statistical and qualitative case study data in order to provide snapshot-in-time or longitudinal analyses of the digital capacities of diverse communities at national, regional and/or local levels. 

This report focuses in on the key findings of in-depth qualitative household case studies conducted with eight Australian families between November 2015 and February 2016. 

The sample comprised a mix of families from diverse socio-economic and cultural backgrounds, including one Indigenous family; a mix of family circumstances, including married, partnered, shared custody and single parent families; and families from urban and regional locations with children aged 12 – 17.

The qualitative interviews were conducted separately with individual family members in the family home. Each semi-structured informal interview lasted on average one and a half hours and included a technology ‘show and tell’, whereby family members showed researchers what digital technologies they had and how they use them.

These case studies allowed the research team to take a holistic and micro level look at how family dynamics impact, shape and even generate digital engagement.  The richness of the qualitative data also informed the development of a quantitative survey instrument. 


### Introducing Digital Capacities

This project defines and measures the digital capacities of Australian families to imagine and mobilise digital media to thrive in their everyday lives. The idea of digital capacities extends on Amartya Sen and Martha Nussbaum’s capabilities approach (Nussbaum, 2011; Sen, 1999), but differs in its starting point.  Drawing on the Circles of Social Life approach (James et al, 2015; Magee, 2016), the Cultivating Digital Capacities project seeks to develop an index that recognizes that human flourishing is not simply embodied in the individual, but relies also on the socially framed capacities that are in constant interaction; that is, the relational agencies and dynamics that are generated by families, communities and social frameworks more generally. 
Digital capacities may manifest in material or structural ways but they also have an imaginative or symbolic dimension; they are about the ways users perceive the affordances of digital media for enhancing their everyday lives and those of the people around them. Whilst benefits are often tangible and quantifiable, capacities are more abstract and therefore can be more challenging to research. Measuring digital capacities requires approaches that can capture users' digital skills and literacies and their lived experiences of using technology. Moreover, they must account for the social, cultural, economic, political and place-based contexts that shape their digital engagement, as well as their aspirations.

Acknowledging the ways our everyday lives are mediated by the digital, researchers, policy makers, practitioners, and technology providers have been interested in measuring how people’s engagements with the digital world impact their lives. By now there are a range of commonly accepted measures that allow us to gain insights into the different ways individuals interact with the digital environment, how they acquire the capacities necessary to navigate their way within that world, and potential barriers to participation. These include measures of access, digital literacy, digital inclusion and so on. 
However, less is known about how to measure the ways in which individuals, along with their communities, utilise social support networks, and their connections with others in the digital world. This is not surprising given the complex array of factors that contribute to those connections at the macro and micro level, and within and beyond the digital world.

Further, many of the measures for digital engagement have focused on the individual as the entity that actualises that engagement, but when we consider the social as the world in which all individuals interact then we are able to shift the emphasis to the importance relationships play in informing how we as families and, indeed, as communities participate in the digital world. As Cordelli writes “relationships can be reasonably regarded as socially-produced, productive resources.”(2015: 110).

Thinking about digital capacities as intrinsically tied to the relationships we produce and engender allows us to discover the types of opportunities afforded by those interactions.

In the qualitative work reported here, along with the quantitative work which is also informing the development of the index, the research team aimed to capture a diverse range of voices and experiences in order to shed some light on the unique ways families have sought to operationalise digital tools and devices in their day-to-day lives. We wanted to find out what motivates their use and how that relates to their family dynamics and social connections. We also wanted to know to what extent safety online was a consideration in the ways in which they interact with the digital world. 

This project has focused on gaining insights into the factors that support families to benefit from the opportunities afforded by the digital world while using technology safely. The Cultivating Digital Capacities project in this phase focuses on two key areas – Social Connectedness and Resilience – which our qualitative work identified as crucial to individuals' and communities' capacities to leverage the opportunities of online engagement. 

The Digital Capacities Index is thus unique as a measure in four respects:

 * Extends existing measures beyond the individual to consider the important role relationships play in the way we all cultivate our digital capacities.

 * Recognizes that rapid changes in technological innovation create a dynamic environment and, within this context, highlights the importance of resilience as a strength that promotes safe, sustainable and positive uses of the internet.

 * Targets relational interactions and dynamics, or social connectedness, as critical to understanding the importance values and attitudes play in cultivating digital capacities.
 
 * Highlights how digital engagement promotes intergenerational relationships in valuable and meaningful ways.


A focus on these areas will assist researchers, policy makers, practitioners and technology providers to expand our understandings of the social dimensions of digital engagement and highlight how the digital world has become embedded in the myriad ways we live our lives today.

In order to shed some light on the ways Australian families are enacting their digital capacities, we highlight here a case study of one family that illustrates some of the project’s key messages. The 2016 theme for Safer Internet Day “Play your part for a better internet” within the broader theme of encouraging safe and positive uses of the internet and digital technologies asks us to think about safety online as a form of resilience; and to recognise how our social interactions both in the online and offline domains help shape our responses to the digital world. The Jones family provide a window into some of the ways Australian families are playing their part in reflectively engaging in the digital world. The Jones family example demonstrates how families who are able to cultivate their digital capacities are enabled to participate both safely and positively in the digital world. 


### Case Study: The Jones Family 

Gabby (mother) and Asu (father) have two children, Sean (son, age 14) and Maggie (daughter, age 12). Gabby and Asu have recently separated and the family is in the process of negotiating that transition in terms of redefining the family dynamics and care of their children. They have shared custody and the children live part time in both households. Both Gabby, and Asu are professionals and the children attend local public schools. The family operate on middle incomes and have medium sized mortgage on both houses. 

Each member of the family has a personal laptop and smart phone, although Maggie does not access the internet on her phone outside of the house. Sean has access to the internet on his phone, but he is on a plan and the data is limited. He sometimes goes over the data limit on his plan – and this is a point of regular negotiation. Both Gabby and Sean also have iPads, which are mostly used for recreational purposes, although Sean sometimes uses his for school when he does not take his laptop. Both the children report not using their laptops all that often. At Asu’s house they mainly watch television series and movies via a digital hard drive to which the content is downloaded. Asu also has a play station that is mainly used by Sean to play first-person shooter games with his cousins.

Although the family have dedicated ‘work stations’, the mobile devices are used in many ‘common’ areas of the house. Family time is valued as something quite separate from engaging with digital devices except when it comes to audiovisual entertainment, which is considered shared family time. The lounge room is the primary location where the family congregate with their individual devices and where they use entertainment platforms such as Netflix and Stan. Maggie has a study where she likes to manage family matters, such as paying bills. She is also a political activist and tends to do this work in that space. Like Gabby, Asu tries to make sure work does not encroach on family time. At Asu’s house, Sean is free to use the internet on his own in his room. Asu describes this as being about developing trust and having a good open dialogue with his children.

All family members can be described as having a good level of digital literacy. Asu and Sean are considered the technological experts in the family. 

> Gabby: Yeah, [Sean]’s good. He’s like his dad. Like, that was always a frustrating thing, like [Asu] knew how to do everything, he’d never show me and then I find Sean is a bit the same when I get really like frustrated. It’s like Oh mum, just calm down. Stop freaking out.

Both Gabby and Maggie are less sure of their capacities to learn new things:

> Gabby: I just like work out a system of how to do it and then I stick to it. But I’m not one of these people that just like, experiments …

> Maggie: Usually I don't know what to do with it, because I don’t really go on it that often. So I ask my brother, because he’s like the technology person. And he’ll help me, yeah. Well I think me and mum are kind of the same. We don’t really know that much about the technology.

Gabby and Asu differ in their digital capacities at work. Gabby, who is a nurse, only really uses technology for email and for compliance issues such as Occupational Health and Safety Training. Asu, who is a designer, has digital technology embedded into everything he does at work. 

> Asu: With work I’m very in touch and up to date with everything. Probably about eighty per cent of my use of technology is mainly work. I use it every day for six, seven hours.

> Gabby: [My workplace] always gets you to do these online courses and stuff. Like mandatory courses that I guess covers them. And you’re just like Oh God, how do you log into this and … I forgot it.

The recent separation between Gabby and Asu highlights tensions in their different attitudes towards negotiating with their children around what is acceptable in terms of their digital engagement. These tensions seem to be related to their different understandings of their own digital capacities and slightly different understandings of and approaches to the level of risk involved in their children’s participation in the digital world. Of particular note is Gabby’s concern about how the violent content of the console games that Sean plays influences his subsequent behaviour. 

> Gabby:… I think the Playstation thing is a really big issue for mums with boys... It was a big issue between me and Asu, because Asu didn’t see it as a problem. But I could see that it changed Sean’s behaviour. 

Asu does not mention the violent content at all. Rather, his concern is about the time it wastes when Sean could be engaged in other activities. At this stage Maggie’s digital activities have not raised any concerns for Gabby or Asu, although there is some awareness that they both need to begin to have more discussions with Maggie about her digital use. 

Gabby and Asu share similar values in terms of their approaches to their children’s access to connectivity, understanding that the digital world is embedded into their everyday lives, and with this come not just risks but opportunities and aspirations. They monitor the children’s access but do not try to place too many restrictions on their use. 

> Asu: I just think that these guys with the way technology is going now and how the education system is going … I think in a few years’ time they won’t need a pen and paper really. They will be doing their exams on laptops and all that stuff, which is brilliant. So I have unlimited internet at my place just because of that.

Gabby and Asu approach issues of safety online with their children as part of their responsibility as parents. They spend time talking to their children about how to discern risk and harm online, while also encouraging them to benefit from the opportunities that the digital world has to offer them.  The family has experienced a fairly complex problem with Sean in terms of bullying and risk through an incident on social media, whereby someone hacked into his account. The approach the family took was to involve Sean in every step of the process to resolve the situation and to talk about what he saw and the content as openly as possible. 

> Asu: We had an issue with Sean, Oh a couple of years ago, where someone set up a Facebook account in his name and that was a bit sort of, stressful. I was very proud of Sean actually. Because he’d say to me Dad, can you come and have a look at this. So I came and had a look at that and it was quite disturbing. ‘I want to kill myself’ dah, dah, dah. I said what’s this? He said I don’t know. Someone … A friend of mine told me about it. And I said well, I’m really sorry son, we’ll try and deal with it. He said ‘Yeah, I don’t mind, it doesn’t bother me really.’ So he was really honest, helpful and didn’t stress out at all about it, which was amazing. I took him with me to the police station. So, everything I did, the emails I sent and all that stuff, he was sitting next to me. And the complaints I did, he was sitting next to me, so he was involved in the whole thing 

Similarly Gabby discussed weighing up the tension between the risks online and the opportunities:

> Gabby: Well, I did try to get Asu to put safety things on for the kids, mainly on the iPads and, phone. But they just don’t work. They just find, they can’t search anything and then they just go onto a different device. They just get frustrated and nag at you all the time. It blocks everything. It blocks way too much.

All members of the family value the opportunities afforded by technology to keep them engaged with their familial networks and their friends. Of particular importance to both Gabby and Asu is maintaining a connection to the family’s ethnic and cultural background. As this background is heavily affected by current geopolitical struggles, both Gabby and Asu are active in raising awareness about the associated humanitarian crisis. Both express concerns about the way issues are portrayed in the media and feel a strong need to help share alternative information and messages via social media. Gabby is particularly vocal on this front, and generates online content around these issues:

> Gabby:  … Because the media is so biased now with this whole conflict and most people are buying it. And one of the biggest reasons for that, all those massive big corps … They’re re-writing history … But when you know people and you keep hearing stories about what’s happening to people. Like, I trust what’s happening because we’ve got family there, who are living this.

For the whole family, the digital world offers a way to stay in contact with family and friends and is their primary motivation for engaging online. Coupled with this, though, family members expressed some level of concern about how much time the digital world can take away from face-to-face contact. 

> Asu : You don’t want to lose that human connection as well, you know. I find that more important than anything else really.

> Sean : I kind of like think it’s wrong that … like, kids of the age of 3 are already starting to be able to like use an iPad really well. It’s kind of weird but like I don't know, start like using technology when you’re about 10  probably or 11, probably be the right age to start technology, for like an hour or two a day. Not over that.

> Gabby: Well … [the internet is] both good and bad … In an ideal world, there’d be no bad and just good stuff and the kids would still get out and about and play around in the streets and not just be sitting at home on their devices. .... Nothing beats that like, personal contact, you know, hanging out with your friends. 

> Maggie: I try to stay off [digital media] at my friends’ places so I can like, talk to my friends in person.

The Jones family have naturalised the role of digital media; they experience it as an inevitable extension of their social world that opens up to a wide range of opportunities. However, digital media also raises challenges that they must deal with on an ongoing basis. These attitudes and dispositions were evident across our sample of Australian families.


### Summary of findings

This project has identified the following key findings about the digital capacities of Australian families:

#### 1. Reflective engagement

AUSTRALIAN FAMILIES ARE ACTIVELY REFLECTING ON THE ROLE THE DIGITAL WORLD PLAYS IN THEIR LIVES AND ARE BEGINNING TO ACKNOWLEDGE THAT DIGITAL MEDIA CAN PLAY A VERY POSITIVE ROLE IN THE LIVES OF FAMILY MEMBERS.  

> I guess I do sort of imagine that world for (Child 1), where she just has more freedom to discover things, you know. I think … I was the sort of kid who imagined all sorts of possibilities that I couldn’t see …Like I always feel as though I was sort of restricted by the environment and the culture around me, which didn’t necessarily suit me all that well. And I feel as though it’s sort of different for (Child 1), because her reference points are just more broad, more open. And it’s not just a small culture that she’s exposed to at any time. She’s got the possibilities of you know listening to any kind of music. You can find like some little band from New York and listen to their latest performance or something, you know. Or like I can’t remember as a kid you know, it was the local radio station or whatever they were playing was the limits of what you had. But now the kids are listening to rap and hip hop and you know, (Child 1) came home last night with a rap that she and her friend had made up. I think that’s really great.

> Single Mum, 39

 * Australian families engage with a diverse range of digital technologies and platforms in their day-to-day lives, and they are actively reflecting on the ways technology supports them to meet challenges and achieve what they want from life. There has been a shift away from the moral panic and doomsday mentalities – ideas about how the digital world will ultimately ruin our lives that were a common trait of the 1990s and early 21st century. Instead, Australian families are developing sophisticated and critical understandings of both the risks and opportunities associated with the digital world. And they are creatively adapting their access and use of digital media to serve a wide range of needs and desires.
 
 * Australian families go online to participate in social and political activism, to pursue cultural and artistic endeavours, to find ways to be more informed citizens and better parents, and to improve their families’ wellbeing.
 
 * Australian families think about both the advantages and disadvantages of technology and generally make informed decisions about when to opt in and when to opt out. Children and parents often draw upon the views of family and friendship networks to make these decisions. Participants wanted to improve their relationships through and beyond digital technology.

 * Although the risks have not decreased or gone away, families increasingly recognize that navigating risk is an ordinary part of life in the digital age. Families also acknowledge that participating safely online is about minimizing the potential for harm through promoting digital literacy and intra-familial dialogue rather than simply blocking content or not allowing children to go online. 

#### 2. Social relationships

Australian families have naturalized the role social media plays in sustaining family relationships and broader friendship networks. 

> If you’re beyond a five kilometre radius of where I live then sure, online would help. But if you’re within five kilometres, I don’t want to see you on the internet, I don’t want to see you online. I want to see you in person. But how can it help? It can just keep people … Keep you informed. It can keep you in touch. Photos I think are great. Videos.  Seeing someone’s place and face, Facetime is revolutionary, I think.
> Dad, 45

 * Social media have become a widely accepted part of the ways Australian families connect with other family members and their broader social networks. The overwhelming majority of families value social media as a means to promote family and friendship networks in sustainable and positive ways, demonstrating significant skill in navigating social media and participating safely. By contrast, though, they often faced challenges with other dimensions of online life, such as paying bills, interfacing with community and government institutions, and understanding how to use technology to support children’s learning. 

#### 3. Family dynamics

Family dynamics are shaped by the diverse and innovative ways in which families adopt and adapt digital technology. 


> Yeah. So quite early on I worked out how to have a shared calendar with someone. I was trying to work out how to make things run smoothly after the separation and have as … minimal contact as possible. I think I was also trying to help him in a way, because I felt as though he was just a little bit removed from (child 1’s) life. And so I thought by creating this mutual calendar, you know, that when I was putting things in that he would know then, when there was an important event coming up. Like, things that he might not have heard about, like, you know, a picnic in the park or assembly, full school assembly or something like that. And then as well, if I’m away I’ll put that in the calendar or he puts his work days in the calendar as well. Because I was having trouble getting a grip on what days he worked and where he was on different days, so he put that in the calendar. And then I extended that actually, just probably a year or two ago, to my parents as well, and they got on board with that.

> Mum, 39


 * In the majority of cases, families use digital media to sustain strong and positive intrafamilial relationships. Those families who demonstrate sound digital capacities use digital media to communicate with and support each other, and to celebrate key family milestones. They also routinely engage in discussion about the role of digital media in daily life; debate and discuss how their family’s values relate to digital media; and share digital expertise across generations. 

 * Some families struggle to manage the role digital media play in their lives and are concerned that digital media undermine family cohesion. These families tend to be those in which the digital literacies of parents do not match those of their children. Policy and practice efforts need to focus more precisely on these groups.

#### 4. Intergenerational dynamics

Children, parents and grandparents see value in engaging online.
> 
> Well I’d like people to sit down and show me, step by step. But they say ‘Give it here I’ll do it’ for you. ‘Oh you do this, you do that’ and then give it back to me and I still don’t know what they’ve done it. They haven’t actually shown me but they’ve told me. Got to sit there and show me, step by step. Well what matters to me doesn’t matter to a lot of my family, you know. Like, what I’m passionate about. This is what I’ve really wanted to learn about, you know.

> Aboriginal Grandma, 65

 * The advent of social media as an important context in which families can maintain connection with each other, their friends and their communities is impacting on the intergenerational take up of digital technologies. Families reported many instances in which family members support one another to experiment with new technologies and platforms and to acquire new skills. However, digital media can also be a source of intergenerational tension. 
 * As different generations build their digital capacities, family dynamics are emerging around who the technology experts are in the family. In particular, gender plays a key role in defining who is a technology expert, with men or boys much more likely to take on this role. This raises questions about how those who have less confidence might be supported to enjoy the benefits of online engagement. 
 * Recognising that peoples’ personal interests play a significant role in their dispositions towards the digital world is important to help them realise their potential as digital participants. This is relevant at all ages.

#### 5. Attitudes to technology

Australian families are best able to maximize the benefits of connectivity when they have positive attitudes towards digital media and effective strategies for navigating risk.

> It’s no difficult for me if sometime I don’t know something, I try to do for different way and then I do. Yeah, because sometimes I saw my children that they do that, they try with this, with that, and then they find the correct way. Then I do the same. I try to do one way or check another way and then I can find. I say Oh there, it’s Ok. 
> 
> Migrant Mother, 50

* Australian families are best positioned to make the most of digital media when they understand how digital media can support them to live well; when they are aware of, and have strategies for dealing with, the risks but are also able to imagine how they can use digital media to achieve their aspirations. It is vital that policy and practice continue to foster digital literacies – the technical skills and higher order evaluative skills – of grandparents, parents and children. As part of this task, there is clear opportunity to further promote positive attitudes towards the role of digital media in day-to-day life. This is key to cultivating and maximizing families’ digital capacities. 

#### 6. Exposure

The digital capacities of Australian families are profoundly shaped by their LEVELS OF exposure to technology. 

> Well, I first started off to communicate, because I’m deaf, and I’d just text people. And that was the only way I could communicate, because I couldn’t hear on the phone and I couldn’t hear very much at all.

> Aboriginal Grandma, 65

 * Exposure to digital media helps Australian families to develop skills and attitudes to leverage the benefits of connectivity. For the adults in this study, the ways they use technology in their working lives is a strong predictor of the ways they use it in their leisure time. Australians who have accepted that technology is a consistent feature of contemporary life are more able to adapt their use of technology to benefit from the opportunities and to respond to challenges of the online world. 


#### 7. Drivers of digital capacities

Australian families are, overall, active and enthusiastic participants in the digital world, helping to shape that world through their daily practices, attitudes to digital technology, and their aspirations for the digital future. Nevertheless, some Australian families, or members of Australian families, still experience barriers to digital participation.

> Our grandchildren are very internet savvy when they search. They do projects on my computer and show me how to you know, take screen photos and …We always used technology, and probably still do, as a substitute for the way we always did things, like reading the newspaper you know, or whatever. Whereas I think the new generation that understands things, understands that it’s data. And as soon as you understand that it’s data then you can see a lot more opportunity because you know, it’s just a matter of how do I use this data. My view is that tthis generation that’s coming through now, will exponentially use technology because they’ll have a far better understanding of its base characteristics, as it becomes more pervasive and kids will just adopt it naturally and be able to do things that we wouldn’t have dreamt of, I’m sure. And I think they probably do already. 

> Grandparents, 68 & 69

 * Social, cultural, economic and geographic factors profoundly shape Australian families’ digital capacities. The perennial problem of distance and mobile coverage is a key concern for some Australian families, as is the affordability of connectivity. Households report that media and regulatory frameworks, as well as the kinds of perspectives and conversation that circulate in the mainstream media, impact on the attitudes Australian families have to issues like online safety.

 * Identity factors structure how digital technology is imagined and practiced. In families the digital capacities of different members of a family are often perceived and organised around factors of gender, cultural background, work histories and age. The issues associated with these factors play a key role in family members’ capacity to leverage the potential of technology; family members have differing levels of confidence when it comes to digital technology. Recognising that peoples’ personal interests and identities play a significant role in their dispositions towards the digital world is important in helping to realise their potential as digital participants. 

#### 8. Parenting in the digital age

The majority of parents are thinking actively about both their own technology use and that of their children. They actively work to adapt those uses to fit their broader philosophies about parenting and family life. 

> I did have a chat to him and say this is not on. I know you’re loving this but there’s other stuff that you have to do. And he found it quite difficult to deal with in the beginning. So I took it away and I said you can’t have it, I can’t have you play with it like that. I don’t want to take it away. I really want you to have some self-control with it, but there has to be limits. And anything over two hours on one day on the weekend I find frustrating, because there’s a lot of stuff that he can be doing 
> 
> Dad, 47 

 * Parents frequently reflect on how, when and why they and their children use digital media. This reflexive attitude towards digital media is evident, for example, in the fact that Australian families worry that they are spending too much time online, and take active steps to balance time online with time offline. They also recognise that going online is increasingly important to many aspects of social life including education, friendship, play, work and creative expression. Staying attentive to the risks that come with their children’s online engagements is a key characteristic of well-developed parental digital capacities. 
 
 * Parents’ own digital capacities shape the ways they understand the risks and opportunities associated with their children’s online engagements, as well as the strategies they use to support their children to engage safely. Many feel their abilities to navigate digital life are lacking, but they also see family members, including their children, as key resources. 
 
 * Parents are generally optimistic about the future of the digital world and participants reported a range of aspirations for their children connected to the digital future. Seniors are more likely to use the internet in very targeted or instrumental ways, such as staying in touch with younger family members, paying bills, etc. 

#### 9. Time online = family time?

Sometimes digital tools provide opportunities for families to spend more time together, to organise their lives, and to promote connection. Sometimes digital technology acts as a barrier to this connection.

> I’m using technology to counter technology. You know, technology is the disease and the cure.
> 
> Single Dad, 45

 * Australian families are concerned about maintaining a balance between time spent online versus time together face-to-face. For those who spend a lot of time online in their work environments, more time online at home can become overwhelming, limiting their motivations to engage with social media and other digitally mediated leisure activities. Similarly some young people experiencing overload if they are online a lot while at school. Face-to-face family time, and time spent outdoors is highly valued and families report that sometimes the digital world seems to encroach too much into those activities.

 * Attitudes towards both the opportunities afforded by digital technology and the ability to opt out vary, depending on a family member’s ability to exercise control over how much technology encroaches into the activities they value in their relationships, alongside their individual interests and responsibilities.

#### 10. Information seeking

Australian families are aware of, and make good use of, the power of information seeking online. 

> And parenting … You know, there are some sites that had resources for parents with mental illness and how to talk to your kids about mental illness. And again, books as well, you know, giving suggestions for books that were helpful in talking about it with kids. 
> Mum, 39

> I’ve used the medical Google to see what is involved in a surgical procedure and what the outcomes are and how long treatment is for and things like that. And vacuum bandaging, which is a new thing. I remember looking that up. 
> Mum, 50

 * Australian families report that they regard online spaces as ones in which people can seek counsel on their own unique life experiences, along with information on how to cope, grow and flourish in the many roles any individual might pilot in life. 
 * Families reported that online information seeking is a part of their day-to-day lives, through activities such as shopping online, checking facts, reading the news, checking the weather and so on. 

#### 11. Alternative access arrangements

Although the model of one device per family member dominates the access debate, some families report that sharing digital devices and tools can generate social capital. 

    I teach my friends how to use an iPad, because like they don’t have iPads. 
    Son, 13 


 * Through the sharing of devices and tools Australian families are demonstrating innovative ways to work around economic and familial complexities to guarantee continuity of connectivity, sustain relationships and to maintain their agency in s difficult circumstances.

 * Some Australian families report that there are instances where the sharing of devices amongst family members and/or their broader networks may lead to opportunities for strengthening interpersonal and community ties; opportunities that are not necessarily afforded by the individualised model of technology access that generally dominates ideas about ‘digital inclusion’ in Australia. As such, the criteria for defining appropriate access may look radically different from one setting to another. Policy and practice might consider redefining access to better reflect the specific conditions under which some families engage online, and to open up to the possible benefits and opportunities that flow from alternative forms of access. 


### References 

Cordelli, C. (2015). Justice as fairness and relational resources. The Journal of Political Philosophy 23(1), 86 – 110. 

James, P. (with Liam Magee, Andy Scerri and Manfred Steger). (2015). Urban sustainability in theory and practice: Circles of sustainability. London: Routledge.

Magee, L. (2016). Interwoven cities. Basingstoke: Palgrave Macmillan.
Nussbaum, Martha C. (2011). Creating capabilities: The human development approach. Cambridge: Harvard University Press. 

Sen, Amartya (1999). Development as freedom. Oxford: Oxford University Press.
