
## Executive Summary

Digital connectivity has become critical to living well in contemporary society. As mobile and networked technologies become ubiquitous, enabling individuals and communities to maximise the benefits of the internet depends on fostering fundamental 21st century capacities. These new capacities are central to the economic, political and cultural life of Australians and must be nurtured from early childhood, and through the life span, in households, workplaces and communities. They encompass the opportunities, skills, attitudes and infrastructures to participate fully, to identify and respond to risks and develop resilience in digital life. Crucially, whilst these capacities are often thought about in individual terms (e.g. the capacity to keep oneself safe online), it is important that we begin to focus debate and target interventions around intergenerational and community-based capacities, as leveraging networks of support is vital in ensuring the maximum safety and participation of all users online.
 
This project offers a unique opportunity to pilot a rigorous and holistic measure of digital capacity. The pilot produces baseline data that can be immediately reported as well as test a methodology for a national rollout of a *Digital Capacity Index*. Such data enables Google – in partnership with government, other corporate, not-for-profit and research organisations – to develop tools, policies, products and services to support the digital capacity of the broadest possible population. 

A unique measure internationally, the *Digital Capacity Index* produces a combination of statistical and qualitative case study data that can be easily manipulated to provide ‘snapshot-in-time’ or longitudinal analysis of digital capacity at national, regional or local levels, as well as to provide information about the digital capacity of diverse communities of interest or experience (e.g. young people, parents). The Index enables Google to track the impacts of tools, and policy and practice interventions on digital capacity in Australia, as well as to identify emerging digital capacity issues over time and across common geographical extents: rural/regional/urban; inner/outer urban; east/west Sydney, and so on. To this end, the Index is an invaluable tool for evaluating Google’s tools, policies and programs that aim to foster digital capacity overall, and specific areas such as safety and participation, and in identifying strategic priorities for the promotion of digital capacity nationally and potentially internationally.

To pilot this index, this project focusses on developing appropriate measures of the digital capacities of Australian families that will yield insights into the intergenerational dynamics and practices shaping connectivity in Australia.
