---
title: "Digital Capacities Index - Quantitative Findings"
author: | 
  | Liam Magee^1^, Delphine Bellerose^1^, Anjali Sharma^1^, Louise Crabtree^1^, Philippa Collin^1^, Justine Humphry^1^, Paul James^1^, Emma Kearney^1^, Tanya Notley^1^, Amanda Third^1^, Samantha Yorke^2^
  | 1. Western Sydney University
  | 2. Google Australia
date: "4 April 2016"
bibliography: DCI.bib
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
  word_document:
    toc: true
    toc_depth: 4
---


<!-- output: html_document -->
<!-- output: word_document -->
<!-- output: pdf_document -->


```{r child='DCI-1-Exec-Summary.Rmd'}
```

```{r child='DCI-2-Conceptual-Framework.Rmd'}
```

```{r child='DCI-3-Literature-Review.Rmd'}
```

```{r child='DCI-4-Methodology.Rmd'}
```

```{r child='DCI-5-Critical-Issues.Rmd'}
```

```{r child='DCI-6-Qualitative-Findings.Rmd'}
```

```{r child='DCI-7-Quantitative-Findings.Rmd'}
```

```{r child='DCI-8-Digital-Capacities-of-Families.Rmd'}
```

```{r child='DCI-9-Setting-the-Agenda.Rmd'}
```


## References


